apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: mongo
type: Opaque
data:
  mongodb-root-password: TW9zdGFmYQ==
  mongodb-password: TW9zdGFmYTI=
  mongodb-replica-set-key: TW9zdGFmYTM=